### ISSUE TITLE
How to get Qbit and Aria Selection webserver working Alpine and MLTB?

### ISSUE THREAD

**Issue by OAJJAIN** [AmirulAndalib/MLTB-ALPINE-DOCKER#8]

**Comment by AmirulAndalib** [comment]
## • Step 1

### First of all go to `bot/__init__.py` and edit the following 👇


![Screenshot_20220907-232829~2](https://user-images.githubusercontent.com/86344856/188941954-41079ae5-1390-47d9-8834-0e38ef5d0aff.png)


---
```python
try:
    LTD = getConfig('LTD')
    if len(LTD) == 0:
        raise KeyError
except:
    log_warning('Localtunnel Domain not provided!')
    LTD = None

try:
    QBIT_LTD = getConfig('QBIT_LTD')
    if len(QBIT_LTD) == 0:
        raise KeyError
except:
    log_warning('Qbittorrent Localtunnel Domain not provided!')
    QBIT_LTD = None

Popen(f"gunicorn web.wserver:app --bind 0.0.0.0:{SERVER_PORT} --timeout 0", shell=True)
Popen(f"lt --subdomain {LTD} --port {SERVER_PORT}" , shell=True)
# Popen(f"lt --subdomain {QBIT_LTD} --port 8090" , shell=True)
srun(["qbittorrent-nox", "-d", "--profile=."])
if not ospath.exists('.netrc'):
    srun(["touch", ".netrc"])
srun(["cp", ".netrc", "/root/.netrc"])
srun(["chmod", "600", ".netrc"])
srun(["chmod", "+x", "aria.sh"])
srun("./aria.sh", shell=True)
sleep(0.5)

```

### extras :

You can uncomment the qbittorrent localtunnel line for qbit web Ui expose .. don't add credentials on qbit gui the bot will crash

---


## • Step 2

### Now Go to `bot/__main__.py` and 
edit the following 

![Screenshot_20220907-233314~2](https://user-images.githubusercontent.com/86344856/188942826-d939c033-567b-419b-af04-382d3a774fc2.png)

---

```python
    srun(["npx", "kill-port", "80"])
    srun(["npx", "kill-port", "8090"])
    srun(["killall", "node"])

---

**Comment by OAJJAIN** [comment]
Working. Sometimes its slow to respond. Also in config.env, those vars should be under "".

**Comment by AmirulAndalib** [comment]
> Working. Sometimes its slow to respond. Also in config.env, those vars should be under "".

Not a problem thank you
