### ISSUE TITLE
I am get an error while using your docker image

### ISSUE THREAD

**Issue by creator-noob** [AmirulAndalib/MLTB-ALPINE-DOCKER#9]
FileNotFoundError: [Errno 2] No such file or directory: 'firefox'
2022-09-18 14:50:53,838 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb81fe43a90>

**Comment by AmirulAndalib** [comment]
repo Not supported for masked apps

Qbit A2c ffmpeg are masked in your repo either rename it and use it or there is no way I can help.

This repo has no masked applications.
